seto_scararobot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

arm_controller:
   type: effort_controllers/JointTrajectoryController
   joints:
     - base_to_arm1
     - arm1_to_arm2
     - end_joint
   gains:
     base_to_arm1:
       p: 100.0
       i: 0.01
       d: 10.0
     arm1_to_arm2:
       p: 100.0
       i: 0.01
       d: 10.0
     end_joint:
       p: 100.0
       i: 0.01
       d: 10.0
