seto_scararobot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

arm_controller:
   type: effort_controllers/JointTrajectoryController
   joints:
     - base_to_arm1
     - arm1_to_arm2
   gains:
     base_to_arm1:
       p: 500.0
       i: 0.1
       d: 50.0
     arm1_to_arm2:
       p: 500.0
       i: 0.1
       d: 50.0
